import { GoogleTagManager } from '@next/third-parties/google';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';

import './globals.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { getHustleSettings } from '@/hustleSettings';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hustleSettings = getHustleSettings();

  return (
    <html lang="en">
      <GoogleTagManager
        gtmId={hustleSettings.GOOGLE_TAG_MANAGER.CONTAINER_ID}
      />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          GeistSans.variable,
          GeistMono.variable,
        )}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
